// swift-tools-version:4.2
import PackageDescription

let package = Package(name: "AdventOfCode2018",
                      products: [
                        .library(name: "AdventOfCode", targets: [ "AdventOfCode" ]),
                        .library(name: "Z3", targets: [ "Z3" ]),
                        .executable(name: "Day1", targets: [ "Day1" ]),
                        .executable(name: "Day2", targets: [ "Day2" ]),
                        .executable(name: "Day3", targets: [ "Day3" ]),
                        .executable(name: "Day4", targets: [ "Day4" ]),
                        .executable(name: "Day5", targets: [ "Day5" ]),
                        .executable(name: "Day6", targets: [ "Day6" ]),
                        .executable(name: "Day7", targets: [ "Day7" ]),
                        .executable(name: "Day8", targets: [ "Day8" ]),
                        .executable(name: "Day9", targets: [ "Day9" ]),
                        .executable(name: "Day10", targets: [ "Day10" ]),
                        .executable(name: "Day11", targets: [ "Day11" ]),
                        .executable(name: "Day12", targets: [ "Day12" ]),
                        .executable(name: "Day13", targets: [ "Day13" ]),
                        .executable(name: "Day14", targets: [ "Day14" ]),
                        .executable(name: "Day15", targets: [ "Day15" ]),
                        .executable(name: "Day16", targets: [ "Day16" ]),
                        .executable(name: "Day17", targets: [ "Day17" ]),
                        .executable(name: "Day18", targets: [ "Day18" ]),
                        .executable(name: "Day19", targets: [ "Day19" ]),
                        .executable(name: "Day20", targets: [ "Day20" ]),
                        .executable(name: "Day21", targets: [ "Day21" ]),
                        .executable(name: "Day22", targets: [ "Day22" ]),
                        .executable(name: "Day23", targets: [ "Day23" ]),
                        .executable(name: "Day24", targets: [ "Day24" ]),
                        .executable(name: "Day25", targets: [ "Day25" ]),
                      ],
                      dependencies: [
                        .package(url: "https://github.com/peterkovacs/FootlessParser.git", .branch( "inout-remainder" )),
                        .package(url: "https://github.com/pointfreeco/swift-tagged.git", from: "0.2.0")
                      ],
                      targets: [
                        .systemLibrary(name: "CZ3"), 
                        .target(name: "Z3", dependencies: ["CZ3", "Tagged"]),
                        .target(name: "AdventOfCode", dependencies: [ "FootlessParser", "Z3" ]),
                        .target(name: "Day1", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day2", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day3", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day4", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day5", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day6", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day7", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day8", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day9", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day10", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day11", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day12", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day13", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day14", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day15", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day16", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day17", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day18", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day19", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day20", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day21", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day22", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day23", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day24", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day25", dependencies: [ "AdventOfCode" ]),
                       ]
 )
